//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMetods.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public card()
        {
            this.orders = new HashSet<order>();
            this.orders1 = new HashSet<order>();
        }
    
        public int card_id { get; set; }
        public string card_number { get; set; }
        public int expiry_month { get; set; }
        public int expiry_year { get; set; }
        public int cvv { get; set; }
        public string cardholder_name { get; set; }
        public Nullable<decimal> cash { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<order> orders1 { get; set; }
    }
}
