//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMetods.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankGatewayEntities : DbContext
    {
        public bankGatewayEntities()
            : base("name=bankGatewayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<card_t> card_t { get; set; }
        public DbSet<card> cards { get; set; }
        public DbSet<order_t> order_t { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<status_t> status_t { get; set; }
        public DbSet<statuss> statusses { get; set; }
    }
}
