//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMetods.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_t
    {
        public status_t()
        {
            this.order_t = new HashSet<order_t>();
        }
    
        public int status_id { get; set; }
        public string mesasage { get; set; }
    
        public virtual ICollection<order_t> order_t { get; set; }
    }
}
